#!/usr/bin/env python3
"""Checks Dak's string resources for translation problems. See docs/i18n.md.

Usage: scripts/check-i18n.py [--android-dir android] [--comments]

Errors (exit 1):
  * a language listed in app/src/main/res/xml/locales_config.xml (so offered to users) has no values-<lang>/ in the
    app, or misses any translatable string of the app or of :core-telephony: only complete languages ship;
  * the first locales_config entry is not the default language ("en") of the unqualified values/;
  * the debug locales_config (which adds pseudo-locales) does not list every release language;
  * a translation's format placeholders (%1$s, %2$d...) or template placeholders ({sender}, {body}...) differ from
    the English string's, or a plural item uses a placeholder the English plural does not;
  * a string with several format placeholders uses non-positional ones (%s %d): translators must be able to
    reorder them;
  * a translation translates a string marked translatable="false".
Warnings (printed, exit 0): values-<lang>/ directories not yet listed in locales_config (work in progress) and,
with --comments, English strings with placeholders but no translator comment.

Runs with the Python standard library only; scripts/tests/test_check_i18n.py covers it (CI runs those tests).
"""

import argparse
import pathlib
import re
import sys
import xml.etree.ElementTree as ET

ANDROID_NS = "{http://schemas.android.com/apk/res/android}"
TOOLS_NS = "{http://schemas.android.com/tools}"
DEFAULT_LANGUAGE = "en"
# Modules whose res/values strings ship in the app. Pseudo-locales are generated by the build, never translated.
MODULES = ("app", "core-telephony")
PSEUDO = {"en-XA", "ar-XB"}

FORMAT_RE = re.compile(r"%(?:(\d+)\$)?[-#+ 0,(]*\d*(?:\.\d+)?([sdfxXcboeEgGaAhHn%])")
BRACE_RE = re.compile(r"\{[A-Za-z][A-Za-z0-9_]*\}")


def tag_to_qualifier(tag):
    """BCP 47 tag -> Android values-* qualifier: hi -> hi, pt-BR -> pt-rBR, zh-Hans-CN -> b+zh+Hans+CN."""
    parts = tag.split("-")
    if len(parts) == 1:
        return parts[0]
    if len(parts) == 2 and re.fullmatch(r"[A-Za-z]{2}|\d{3}", parts[1]):
        return f"{parts[0]}-r{parts[1].upper()}"
    return "b+" + "+".join(parts)


def read_locale_config(path):
    if not path.exists():
        return None
    root = ET.parse(path).getroot()
    return [e.get(ANDROID_NS + "name") for e in root.iter("locale")]


def _text(elem):
    return "".join(elem.itertext())


def read_strings(values_dir):
    """{name: (kind, texts, translatable, has_comment)} for strings and plurals in one values dir."""
    out = {}
    if not values_dir.is_dir():
        return out
    for f in sorted(values_dir.glob("*.xml")):
        try:
            root = ET.parse(f, parser=ET.XMLParser(target=ET.TreeBuilder(insert_comments=True))).getroot()
        except ET.ParseError as e:
            raise SystemExit(f"{f}: {e}")
        if root.tag != "resources":
            continue
        previous_comment = False
        for child in root:
            if child.tag is ET.Comment:
                previous_comment = True
                continue
            name = child.get("name")
            translatable = child.get("translatable", "true") != "false"
            if child.tag == "string":
                out[name] = ("string", [_text(child)], translatable, previous_comment, f.name)
            elif child.tag == "plurals":
                out[name] = ("plurals", [_text(i) for i in child.iter("item")], translatable, previous_comment, f.name)
            previous_comment = False
    return out


def placeholders(text):
    """(positional format placeholders as a set of (index, conversion), brace placeholders)."""
    fmt = set()
    implicit = 0
    for m in FORMAT_RE.finditer(text):
        index, conv = m.group(1), m.group(2)
        if conv in "%n":
            continue
        if index is None:
            implicit += 1
            index = str(implicit)
        fmt.add((index, conv))
    return fmt, set(BRACE_RE.findall(text))


def non_positional_count(text):
    return sum(1 for m in FORMAT_RE.finditer(text) if m.group(1) is None and m.group(2) not in "%n")


def check(android_dir, comments=False):
    errors, warnings = [], []
    app_res = android_dir / "app/src/main/res"
    config = read_locale_config(app_res / "xml/locales_config.xml")
    debug_config = read_locale_config(android_dir / "app/src/debug/res/xml/locales_config.xml")
    if not config:
        errors.append("app/src/main/res/xml/locales_config.xml is missing or empty")
        config = [DEFAULT_LANGUAGE]
    if config[0] != DEFAULT_LANGUAGE:
        errors.append(f"locales_config.xml: first entry must be the default language '{DEFAULT_LANGUAGE}', got '{config[0]}'")
    if debug_config is not None:
        missing = [t for t in config if t not in debug_config]
        if missing:
            errors.append(f"debug locales_config.xml lacks release languages {missing}")
    for tag in config:
        if tag in PSEUDO:
            errors.append(f"locales_config.xml lists pseudo-locale {tag}: only the debug copy may")

    defaults = {m: read_strings(android_dir / m / "src/main/res/values") for m in MODULES}
    for module, strings in defaults.items():
        for name, (kind, texts, translatable, has_comment, fname) in strings.items():
            for t in texts:
                fmt, braces = placeholders(t)
                if len(fmt) > 1 and non_positional_count(t):
                    errors.append(f"{module}/{fname}: {name} has several placeholders; use %1$s, %2$d... so translators can reorder")
                if comments and translatable and (fmt or braces) and not has_comment:
                    warnings.append(f"{module}/{fname}: {name} has placeholders but no translator comment")

    # Every translation directory present, listed or not.
    languages = set()
    for module in MODULES:
        res = android_dir / module / "src/main/res"
        for d in res.glob("values-*"):
            if read_strings(d):
                languages.add(d.name[len("values-"):])
    listed = {tag_to_qualifier(t): t for t in config[1:]}
    for q in sorted(languages - set(listed)):
        warnings.append(f"values-{q}/ exists but is not in locales_config.xml (not offered to users yet)")

    for q in sorted(languages | set(listed)):
        shipping = q in listed
        for module in MODULES:
            base = defaults[module]
            translated = read_strings(android_dir / module / "src/main/res" / f"values-{q}")
            if shipping and module == "app" and not (android_dir / module / "src/main/res" / f"values-{q}").is_dir():
                errors.append(f"{listed[q]} is in locales_config.xml but app/src/main/res/values-{q}/ does not exist")
            for name, (kind, texts, translatable, _, fname) in base.items():
                if not translatable:
                    if name in translated:
                        errors.append(f"{module} values-{q}: {name} is translatable=\"false\" but translated")
                    continue
                if name not in translated:
                    if shipping:
                        errors.append(f"{module} values-{q}: missing {name} ({listed[q]} ships, so it must be complete)")
                    continue
                base_fmt = set().union(*(placeholders(t)[0] for t in texts)) if texts else set()
                base_braces = set().union(*(placeholders(t)[1] for t in texts)) if texts else set()
                for t in translated[name][1]:
                    fmt, braces = placeholders(t)
                    if kind == "string" and (fmt != base_fmt or braces != base_braces):
                        errors.append(
                            f"{module} values-{q}: {name} placeholders {sorted(fmt | braces)} != English {sorted(base_fmt | base_braces)}"
                        )
                    elif kind == "plurals" and (not fmt <= base_fmt or braces != base_braces):
                        # A plural item may drop the count (e.g. "one" -> "a message"), never invent one.
                        errors.append(f"{module} values-{q}: plural {name} item uses {sorted(fmt | braces)} not in English")
            for name in translated:
                if name not in base:
                    warnings.append(f"{module} values-{q}: {name} is not in the English strings (stale)")
    return errors, warnings


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--android-dir", default=str(pathlib.Path(__file__).resolve().parent.parent))
    ap.add_argument("--comments", action="store_true", help="also warn about placeholder strings without a comment")
    args = ap.parse_args(argv)
    errors, warnings = check(pathlib.Path(args.android_dir), comments=args.comments)
    for w in warnings:
        print(f"warning: {w}")
    for e in errors:
        print(f"error: {e}")
    print(f"check-i18n: {len(errors)} error(s), {len(warnings)} warning(s)")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
