package app.dak.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/*
 * Designed fallback palette (teal seed) used below Android 12, when dynamic colour is off, and for high contrast.
 * Values follow the Material 3 tonal system so text roles meet WCAG AA on their containers.
 */

internal val DakLightScheme: ColorScheme = lightColorScheme(
    primary = Color(0xFF006A6A),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFF9CF1F0),
    onPrimaryContainer = Color(0xFF002020),
    inversePrimary = Color(0xFF80D5D4),
    secondary = Color(0xFF4A6363),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFCCE8E7),
    onSecondaryContainer = Color(0xFF051F1F),
    tertiary = Color(0xFF4B607C),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFD3E4FF),
    onTertiaryContainer = Color(0xFF041C35),
    background = Color(0xFFF4FBFA),
    onBackground = Color(0xFF161D1D),
    surface = Color(0xFFF4FBFA),
    onSurface = Color(0xFF161D1D),
    surfaceVariant = Color(0xFFDAE5E4),
    onSurfaceVariant = Color(0xFF3F4948),
    surfaceTint = Color(0xFF006A6A),
    inverseSurface = Color(0xFF2B3231),
    inverseOnSurface = Color(0xFFECF2F1),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    outline = Color(0xFF6F7979),
    outlineVariant = Color(0xFFBEC9C8),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFF4FBFA),
    surfaceContainer = Color(0xFFE9EFEE),
    surfaceContainerHigh = Color(0xFFE3E9E9),
    surfaceContainerHighest = Color(0xFFDDE4E3),
    surfaceContainerLow = Color(0xFFEEF5F4),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceDim = Color(0xFFD5DBDA),
)

internal val DakDarkScheme: ColorScheme = darkColorScheme(
    primary = Color(0xFF80D5D4),
    onPrimary = Color(0xFF003737),
    primaryContainer = Color(0xFF004F4F),
    onPrimaryContainer = Color(0xFF9CF1F0),
    inversePrimary = Color(0xFF006A6A),
    secondary = Color(0xFFB0CCCB),
    onSecondary = Color(0xFF1B3534),
    secondaryContainer = Color(0xFF324B4B),
    onSecondaryContainer = Color(0xFFCCE8E7),
    tertiary = Color(0xFFB3C8E8),
    onTertiary = Color(0xFF1C314B),
    tertiaryContainer = Color(0xFF334863),
    onTertiaryContainer = Color(0xFFD3E4FF),
    background = Color(0xFF0E1514),
    onBackground = Color(0xFFDDE4E3),
    surface = Color(0xFF0E1514),
    onSurface = Color(0xFFDDE4E3),
    surfaceVariant = Color(0xFF3F4948),
    onSurfaceVariant = Color(0xFFBEC9C8),
    surfaceTint = Color(0xFF80D5D4),
    inverseSurface = Color(0xFFDDE4E3),
    inverseOnSurface = Color(0xFF2B3231),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    outline = Color(0xFF889392),
    outlineVariant = Color(0xFF3F4948),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF343A3A),
    surfaceContainer = Color(0xFF1A2121),
    surfaceContainerHigh = Color(0xFF252B2B),
    surfaceContainerHighest = Color(0xFF2F3636),
    surfaceContainerLow = Color(0xFF161D1D),
    surfaceContainerLowest = Color(0xFF090F0F),
    surfaceDim = Color(0xFF0E1514),
)

/** High-contrast light: darker primaries and pure-black text roles (roughly 7:1 on surfaces). */
internal val DakLightHighContrastScheme: ColorScheme = DakLightScheme.copy(
    primary = Color(0xFF003B3B),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFF005151),
    onPrimaryContainer = Color(0xFFFFFFFF),
    secondary = Color(0xFF223B3B),
    secondaryContainer = Color(0xFF3A5353),
    onSecondaryContainer = Color(0xFFFFFFFF),
    tertiary = Color(0xFF223850),
    tertiaryContainer = Color(0xFF384D69),
    onTertiaryContainer = Color(0xFFFFFFFF),
    background = Color(0xFFFFFFFF),
    surface = Color(0xFFFFFFFF),
    onBackground = Color(0xFF000000),
    onSurface = Color(0xFF000000),
    onSurfaceVariant = Color(0xFF1C2525),
    outline = Color(0xFF3B4545),
    outlineVariant = Color(0xFF5A6464),
    error = Color(0xFF7A0000),
    errorContainer = Color(0xFF9E0E0E),
    onErrorContainer = Color(0xFFFFFFFF),
)

/** High-contrast dark: lighter primaries and pure-white text roles. */
internal val DakDarkHighContrastScheme: ColorScheme = DakDarkScheme.copy(
    primary = Color(0xFFBEFFFE),
    onPrimary = Color(0xFF000000),
    primaryContainer = Color(0xFF84D9D8),
    onPrimaryContainer = Color(0xFF000000),
    secondary = Color(0xFFDDF9F8),
    secondaryContainer = Color(0xFFB4D0CF),
    onSecondaryContainer = Color(0xFF000000),
    tertiary = Color(0xFFEAF1FF),
    tertiaryContainer = Color(0xFFB7CCEC),
    onTertiaryContainer = Color(0xFF000000),
    background = Color(0xFF000000),
    surface = Color(0xFF000000),
    onBackground = Color(0xFFFFFFFF),
    onSurface = Color(0xFFFFFFFF),
    onSurfaceVariant = Color(0xFFF2FDFC),
    outline = Color(0xFFBAC5C4),
    outlineVariant = Color(0xFFBAC5C4),
    error = Color(0xFFFFECE9),
    errorContainer = Color(0xFFFFBAB1),
    onErrorContainer = Color(0xFF000000),
)

/** Turns a dark scheme into its true-black (AMOLED) variant: pure-black surfaces, near-black containers. */
internal fun ColorScheme.toAmoled(): ColorScheme = copy(
    background = Color.Black,
    surface = Color.Black,
    surfaceDim = Color.Black,
    surfaceContainerLowest = Color.Black,
    surfaceContainerLow = Color(0xFF0A0A0A),
    surfaceContainer = Color(0xFF121212),
    surfaceContainerHigh = Color(0xFF1A1A1A),
    surfaceContainerHighest = Color(0xFF222222),
    surfaceBright = Color(0xFF2A2A2A),
    inverseOnSurface = Color.Black,
)
