#!/usr/bin/env python3
"""Generates the compact Unicode tables :classify uses for text safety (UTS #46 and UTS #39).

The Unicode data files are not checked in (about 4 MB). Download them for the pinned version, then run:

    python3 android/classify/tools/gen_unicode_tables.py --src <dir with the files below>

Source files (Unicode 17.0.0; the unicode.org copies are identical to the unicode-org/unicodetools ones):

    https://www.unicode.org/Public/idna/17.0.0/IdnaMappingTable.txt          (UTS #46)
    https://www.unicode.org/Public/security/17.0.0/confusables.txt          (UTS #39)
    https://www.unicode.org/Public/17.0.0/ucd/Scripts.txt
    https://www.unicode.org/Public/17.0.0/ucd/extracted/DerivedJoiningType.txt
    https://www.unicode.org/Public/17.0.0/ucd/extracted/DerivedCombiningClass.txt
    https://www.unicode.org/Public/idna/17.0.0/IdnaTestV2.txt               (only for --test-vectors)
    https://www.unicode.org/Public/17.0.0/ucd/DerivedAge.txt                (only for --test-vectors)

Outputs (under android/classify/src/main/resources/app/dak/classify/unicode/):

    idna-mapping.txt   every code point's UTS #46 status (valid / mapped / deviation / ignored / disallowed) and
                       mapping, as ranges: "<start> <V|M|O|D|I|X> [<mapping>]"; a range runs to the next start. M maps
                       every code point of the range to the listed code points; O maps each one to itself plus the
                       listed (signed, hex) offset.
    idna-context.txt   what CONTEXTJ (RFC 5892 appendix A.1/A.2) needs: Joining_Type L/D/R/T ranges and the
                       Canonical_Combining_Class=9 (virama) code points.
    confusables.txt    the UTS #39 confusables (MA) mapping, restricted to source characters of the scripts SMS
                       phishing uses against Indian users and to Common/Inherited (digits, symbols, fullwidth and
                       mathematical letters): "<source> <target code points>".

With --test-vectors it also writes a filtered IdnaTestV2 subset to the test resources (rows whose characters are
all in Unicode 13.0 or older, so the JVM's own NFC and Bidi_Class data agree with the table).
"""
import argparse
import hashlib
import os
import re
import sys
import unicodedata

# Scripts whose characters get confusables entries. Latin, Cyrillic, Greek, Armenian and Cherokee are the homograph
# sources for Latin brand names; Devanagari and Bengali (and Common/Inherited: digits, symbols, fullwidth, math
# alphanumerics) cover the scripts and number forms Indian senders use.
CONFUSABLE_SCRIPTS = {"Latin", "Cyrillic", "Greek", "Armenian", "Cherokee", "Devanagari", "Bengali", "Common", "Inherited"}

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(HERE, "..", "src", "main", "resources", "app", "dak", "classify", "unicode")
TEST_RES = os.path.join(HERE, "..", "src", "test", "resources", "app", "dak", "classify", "unicode")


def sha256(path):
    with open(path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()


def version_of(path):
    with open(path, encoding="utf-8-sig") as f:
        for line in f:
            m = re.match(r"#\s*(?:Version:\s*|\w+-)(\d+\.\d+\.\d+)", line)
            if m:
                return m.group(1)
    raise SystemExit(f"no version header in {path}")


def data_lines(path):
    with open(path, encoding="utf-8-sig") as f:
        for line in f:
            body = line.split("#", 1)[0].strip()
            if body:
                yield [field.strip() for field in body.split(";")]


def cp_range(field):
    if ".." in field:
        a, b = field.split("..")
        return int(a, 16), int(b, 16)
    return int(field, 16), int(field, 16)


def header(out, src_files, what):
    out.write(f"# Generated by android/classify/tools/gen_unicode_tables.py: {what}. Do not edit.\n")
    out.write("# Unicode data (c) Unicode, Inc., Unicode License v3: https://www.unicode.org/license.txt\n")
    for p in src_files:
        out.write(f"# Source: {os.path.basename(p)} {version_of(p)} sha256={sha256(p)}\n")


def gen_idna(src, out_dir):
    path = os.path.join(src, "IdnaMappingTable.txt")
    code = {"valid": "V", "mapped": "M", "deviation": "D", "ignored": "I", "disallowed": "X"}
    ranges = []
    for fields in data_lines(path):
        lo, hi = cp_range(fields[0])
        st = code[fields[1]]
        mapping = fields[2] if len(fields) > 2 and st in "MD" else ""
        if st == "D":
            mapping = ""  # nontransitional processing: deviations stay as they are (valid)
        ranges.append((lo, hi, st, mapping))
    ranges.sort()
    # Merge adjacent ranges with the same status and mapping (mapped ranges only when the mapping is identical).
    merged = []
    expect = 0
    for lo, hi, st, mapping in ranges:
        if lo != expect:
            raise SystemExit(f"gap before {lo:04X}")
        expect = hi + 1
        if st == "M" and " " not in mapping and lo == hi:
            # A single code point mapped to a single code point: store the offset, so runs like A-Z -> a-z are one line.
            st, mapping = "O", "%X" % (int(mapping, 16) - lo) if int(mapping, 16) >= lo else "-%X" % (lo - int(mapping, 16))
        if merged and merged[-1][2] == st and merged[-1][3] == mapping and merged[-1][1] + 1 == lo:
            merged[-1] = (merged[-1][0], hi, st, mapping)
        else:
            merged.append((lo, hi, st, mapping))
    if expect != 0x110000:
        raise SystemExit("table does not reach 10FFFF")
    with open(os.path.join(out_dir, "idna-mapping.txt"), "w", encoding="utf-8", newline="\n") as out:
        header(out, [path], "UTS #46 IDNA mapping table, nontransitional")
        for lo, hi, st, mapping in merged:
            out.write(f"{lo:X} {st}" + (f" {mapping}" if mapping else "") + "\n")
    return len(merged)


def gen_context(src, out_dir):
    jt_path = os.path.join(src, "DerivedJoiningType.txt")
    ccc_path = os.path.join(src, "DerivedCombiningClass.txt")
    joins = []
    for fields in data_lines(jt_path):
        lo, hi = cp_range(fields[0])
        if fields[1] in ("L", "D", "R", "T"):
            joins.append((lo, hi, fields[1]))
    joins.sort()
    merged = []
    for lo, hi, t in joins:
        if merged and merged[-1][2] == t and merged[-1][1] + 1 == lo:
            merged[-1] = (merged[-1][0], hi, t)
        else:
            merged.append((lo, hi, t))
    viramas = []
    for fields in data_lines(ccc_path):
        if fields[1] == "9":
            lo, hi = cp_range(fields[0])
            viramas.extend(range(lo, hi + 1))
    with open(os.path.join(out_dir, "idna-context.txt"), "w", encoding="utf-8", newline="\n") as out:
        header(out, [jt_path, ccc_path], "Joining_Type L/D/R/T ranges and virama (ccc=9) code points for CONTEXTJ")
        for lo, hi, t in merged:
            out.write(f"J {lo:X} {hi:X} {t}\n")
        for v in sorted(viramas):
            out.write(f"V {v:X}\n")
    return len(merged), len(viramas)


def scripts_of(src):
    path = os.path.join(src, "Scripts.txt")
    table = {}
    for fields in data_lines(path):
        lo, hi = cp_range(fields[0])
        for cp in range(lo, hi + 1):
            table[cp] = fields[1]
    return path, table


def gen_confusables(src, out_dir):
    path = os.path.join(src, "confusables.txt")
    scripts_path, scripts = scripts_of(src)
    rows = []
    for fields in data_lines(path):
        if len(fields) < 3 or fields[2] != "MA":
            continue
        source = int(fields[0], 16)
        if scripts.get(source, "Unknown") not in CONFUSABLE_SCRIPTS:
            continue
        rows.append((source, fields[1]))
    rows.sort()
    with open(os.path.join(out_dir, "confusables.txt"), "w", encoding="utf-8", newline="\n") as out:
        header(out, [path, scripts_path], "UTS #39 confusables (MA) for " + ", ".join(sorted(CONFUSABLE_SCRIPTS)))
        for source, target in rows:
            out.write(f"{source:X} {target}\n")
    return len(rows)


def gen_test_vectors(src, out_dir):
    """IdnaTestV2 rows usable on a JVM whose Unicode data may be as old as 13.0 (see module docstring)."""
    path = os.path.join(src, "IdnaTestV2.txt")
    age_ok = assigned_by_13(src)
    kept = 0
    with open(os.path.join(out_dir, "IdnaTestV2-subset.txt"), "w", encoding="utf-8", newline="\n") as out:
        header(out, [path], "IdnaTestV2 rows limited to Unicode 13.0 characters (fields: source; toUnicode; "
                            "toUnicodeStatus; toAsciiN; toAsciiNStatus)")
        for fields in data_lines(path):
            source = unescape(fields[0])
            to_unicode = unescape(fields[1]) if fields[1] else source
            if not all(age_ok(ord(c)) for c in source + to_unicode):
                continue
            out.write("; ".join(fields[:5]) + "\n")
            kept += 1
    return kept


def assigned_by_13(src):
    path = os.path.join(src, "DerivedAge.txt")
    if not os.path.exists(path):
        # Without DerivedAge, fall back to Python's own (older) Unicode database: anything it knows is old enough.
        return lambda cp: unicodedata.category(chr(cp)) != "Cn" or cp in (0xFFFE, 0xFFFF)
    ok = set()
    for fields in data_lines(path):
        major, minor = (int(x) for x in fields[1].split("."))
        if (major, minor) <= (13, 0):
            lo, hi = cp_range(fields[0])
            ok.update(range(lo, hi + 1))
    return lambda cp: cp in ok or cp < 0x80


def unescape(s):
    return re.sub(r"\\u([0-9A-Fa-f]{4})|\\x\{([0-9A-Fa-f]+)\}", lambda m: chr(int(m.group(1) or m.group(2), 16)), s)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--src", required=True, help="directory holding the Unicode source files")
    parser.add_argument("--test-vectors", action="store_true", help="also write the IdnaTestV2 subset")
    args = parser.parse_args()
    os.makedirs(RES, exist_ok=True)
    print("idna-mapping.txt ranges:", gen_idna(args.src, RES))
    print("idna-context.txt (joining ranges, viramas):", gen_context(args.src, RES))
    print("confusables.txt entries:", gen_confusables(args.src, RES))
    if args.test_vectors:
        os.makedirs(TEST_RES, exist_ok=True)
        print("IdnaTestV2-subset.txt rows:", gen_test_vectors(args.src, TEST_RES))


if __name__ == "__main__":
    sys.exit(main())
